import { Trade_Winds, Montserrat } from "next/font/google";
import "./globals.css";
import Nav from "./ui/common/Nav";

const tradeWinds = Trade_Winds({
  variable: "--font-trade-winds",
  subsets: ["latin"],
  weight: "400",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${tradeWinds.variable} ${montserrat.variable} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
